# Generated by Django 5.0.7 on 2024-09-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_rentlist_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryIcon',
            field=models.ImageField(default=None, upload_to='icons/'),
            preserve_default=False,
        ),
    ]
