# Generated by Django 5.1.1 on 2024-09-29 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rules_categories_category_image_rentitem_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentitem',
            old_name='latiude',
            new_name='latitude',
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
