# Generated by Django 5.1.1 on 2024-10-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rentitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category_image',
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
    ]
