# Generated by Django 5.1.1 on 2024-10-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_categories_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
    ]
