# Generated by Django 5.1.1 on 2024-10-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_rentitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
