# Generated by Django 5.1.1 on 2024-10-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_rentitem_latitude_alter_rentitem_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
