# Generated by Django 5.1.1 on 2024-10-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
