# Generated by Django 5.1.1 on 2024-10-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_rentitem_latitude_alter_rentitem_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentitem',
            name='category',
        ),
    ]
