# Generated by Django 5.1.1 on 2024-10-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_rentitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentitem',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='base.categories'),
            preserve_default=False,
        ),
    ]
