# Generated by Django 5.1.1 on 2024-10-16 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rentitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_category', to='base.categories'),
        ),
    ]
