# Generated by Django 5.1.1 on 2024-10-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_rentitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentitem',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='rentitem',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='rentitem',
            old_name='quantity',
            new_name='inStock',
        ),
        migrations.AddField(
            model_name='rentitem',
            name='status',
            field=models.CharField(choices=[('VF', 'Verified'), ('NVF', 'Not Verified')], default='NVF', max_length=4),
        ),
    ]
