# Generated by Django 5.1.1 on 2024-12-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_booking_rentitems_alter_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentitem',
            old_name='users',
            new_name='owner',
        ),
    ]
